services:

  base-datos:
    image: gvenzl/oracle-free:latest
    container_name: oracle-hotel
    environment:
      ORACLE_PASSWORD: "1469370"
      APP_USER: "hotel"
      APP_USER_PASSWORD: "1469371"
    ports:
      - "1522:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 180s


  app-web:
    build: .
    container_name: hotelbook
    ports:
      - "8080:8080"
    depends_on:
      - base-datos

    environment:

      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@base-datos:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: "hotel"
      SPRING_DATASOURCE_PASSWORD: "1469371"

      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.OracleDialect

volumes:
  oracle_data: